sudo: required

language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - CI=true yarn run test
  - yarn run build
on:
  branch: master
