sudo: required

language: node_js

services:
  - mysql

env:
  - DB: mysql

before_script:
  - export NODE_ENV=production
  - export HTTPS=true

node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn run test
  - yarn run build
on:
  branch: master
