sudo: required

language: node_js

services:
  - docker

before_install:
  - docker-compose --version
  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker-compose start
  - docker ps

node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn run test
  - yarn run build
on:
  branch: master